title = "Davids Blog"
author = "David Wallace"
theme = "contrast-hugo"

[params]
  minimal = false
  excerpts = false
  description = "my blog"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
